### ISSUE TITLE
Question: LFEBL vs LFEPBL

### ISSUE THREAD

**Issue by sy2002** [amb5l/tyto_project#4]
While merging @amb5l 's newest commit b98fe33387bd27242c1005558aa7e96c006fc9a3 into "our" / @gardners version of the source, I noticed, that Adam is using something called "LFEPBL" while Paul uses "LFEBL".

I need to admit that I have no idea what this means and just wanted to make sure, that neither Paul nor Adam is having a typo.

Please see this screenshot: 
<img width="1791" alt="grafik" src="https://user-images.githubusercontent.com/6825267/125208122-f5af3380-e290-11eb-9f22-fc64962e462c.png">

Question to @amb5l : Shall I merge your LFEPBL or keep Paul's LFEBL ?

**Comment by amb5l** [comment]
LFEBL was a typo. The field should always have been called LFEPBL ("LFE PlayBack Level" related to subwoofers etc).

**Comment by sy2002** [comment]
Thank you.
